/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PrimeXMMarginRequirementBreakdown {
  /** Base margin requirement component. */
  @JsonProperty("base_margin")
  private String baseMargin;

  /** Volatility add-on component. */
  @JsonProperty("volatility_addon")
  private String volatilityAddon;

  /** Liquidity add-on component. */
  @JsonProperty("liquidity_addon")
  private String liquidityAddon;

  /** Credits that offset margin charges due to portfolio composition. */
  @JsonProperty("offset_credit")
  private String offsetCredit;

  /**
   * Futures margin charge applied for any futures trades of the opposing direction but of the same
   * underlying.
   */
  @JsonProperty("futures_margin")
  private String futuresMargin;

  public PrimeXMMarginRequirementBreakdown() {}

  public PrimeXMMarginRequirementBreakdown(Builder builder) {
    this.baseMargin = builder.baseMargin;
    this.volatilityAddon = builder.volatilityAddon;
    this.liquidityAddon = builder.liquidityAddon;
    this.offsetCredit = builder.offsetCredit;
    this.futuresMargin = builder.futuresMargin;
  }

  public String getBaseMargin() {
    return baseMargin;
  }

  public void setBaseMargin(String baseMargin) {
    this.baseMargin = baseMargin;
  }

  public String getVolatilityAddon() {
    return volatilityAddon;
  }

  public void setVolatilityAddon(String volatilityAddon) {
    this.volatilityAddon = volatilityAddon;
  }

  public String getLiquidityAddon() {
    return liquidityAddon;
  }

  public void setLiquidityAddon(String liquidityAddon) {
    this.liquidityAddon = liquidityAddon;
  }

  public String getOffsetCredit() {
    return offsetCredit;
  }

  public void setOffsetCredit(String offsetCredit) {
    this.offsetCredit = offsetCredit;
  }

  public String getFuturesMargin() {
    return futuresMargin;
  }

  public void setFuturesMargin(String futuresMargin) {
    this.futuresMargin = futuresMargin;
  }

  public static class Builder {
    private String baseMargin;

    private String volatilityAddon;

    private String liquidityAddon;

    private String offsetCredit;

    private String futuresMargin;

    public Builder baseMargin(String baseMargin) {
      this.baseMargin = baseMargin;
      return this;
    }

    public Builder volatilityAddon(String volatilityAddon) {
      this.volatilityAddon = volatilityAddon;
      return this;
    }

    public Builder liquidityAddon(String liquidityAddon) {
      this.liquidityAddon = liquidityAddon;
      return this;
    }

    public Builder offsetCredit(String offsetCredit) {
      this.offsetCredit = offsetCredit;
      return this;
    }

    public Builder futuresMargin(String futuresMargin) {
      this.futuresMargin = futuresMargin;
      return this;
    }

    public PrimeXMMarginRequirementBreakdown build() {
      return new PrimeXMMarginRequirementBreakdown(this);
    }
  }
}
