/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.enums.RewardSubtype;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class RewardMetadata {
    /**
     * - REWARD_SUBTYPE_UNKNOWN: An unknown reward subtype, reward subtype may not be supported in the API response yet - MEV_REWARD: A maximal extractable value reward i.e. sol mev rewards - INFLATION_REWARD: An inflationary reward i.e. solana inflationary rewards - BLOCK_REWARD: A block reward i.e. solana block rewards - VALIDATOR_REWARD: A validator reward i.e. ethereum validator (consensus layer) rewards - TRANSACTION_REWARD: A transaction reward i.e. ethereum transaction (execution layer) rewards - STAKING_FEE_REBATE_REWARD: A staking fee rebate reward i.e. coinbase pays rebates for staking fees to eligible delegators - BUIDL_DIVIDEND: A BUIDL dividend reward i.e. dividends from BUIDL fund holdings
     */
    @JsonProperty("subtype")
    private RewardSubtype subtype;

    public RewardMetadata() {
    }

    public RewardMetadata(Builder builder) {
        this.subtype = builder.subtype;
    }
    public RewardSubtype getSubtype() {
        return subtype;
    }

    public void setSubtype(RewardSubtype subtype) {
        this.subtype = subtype;
    }
    public static class Builder {
        private RewardSubtype subtype;

        public Builder subtype(RewardSubtype subtype) {
            this.subtype = subtype;
            return this;
        }

        public RewardMetadata build() {
            return new RewardMetadata(this);
        }
    }
}

