/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model.enums;

/**
 * - EXPIRING_CONTRACT_STATUS_UNKNOWN: Unknown/unset — returns all expiring contracts (backward
 * compatible default) - EXPIRING_CONTRACT_STATUS_UNEXPIRED: Only unexpired contracts
 * (contract_expiry is in the future) - EXPIRING_CONTRACT_STATUS_EXPIRED: Only expired contracts
 * (contract_expiry is in the past) - EXPIRING_CONTRACT_STATUS_ALL: All contracts regardless of
 * expiry status
 */
public enum ExpiringContractStatus {
  /** Only unexpired contracts (contract_expiry is in the future) */
  EXPIRING_CONTRACT_STATUS_UNEXPIRED,
  /** Only expired contracts (contract_expiry is in the past) */
  EXPIRING_CONTRACT_STATUS_EXPIRED,
  /** All contracts regardless of expiry status */
  EXPIRING_CONTRACT_STATUS_ALL
}
